[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.121.0"
  HUGO_ENV = "production"

[context.production]
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
